### ISSUE TITLE
Global Resources fix order of items on mobile

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#123]
https://main--ororafresh--hlxsites.hlx.live/about-us

<img width="336" alt="Screenshot 2023-07-20 at 14 50 18" src="https://github.com/hlxsites/ororafresh/assets/111385/b5ff6189-56f3-4473-9007-29c109096024">

**Comment by meejain** [comment]
@paolomoz  - The issue is fixed as per https://github.com/hlxsites/ororafresh/pull/136
