### ISSUE TITLE
Images in columns not size/position correctly at some window width

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#127]
https://main--ororafresh--hlxsites.hlx.live/produce-packaging-solutions

<img width="511" alt="Screenshot 2023-07-20 at 15 05 22" src="https://github.com/hlxsites/ororafresh/assets/111385/d5c1dd6c-c13b-4aac-905f-5a25e1b7e512">

**Comment by meejain** [comment]
Fixed as per https://github.com/hlxsites/ororafresh/pull/133. Please check & validate further . 

https://images-column-issue-127--ororafresh--hlxsites.hlx.live/drafts/Meet/produce-packaging-solutions
