### ISSUE TITLE
Back to top icon not found on .live

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#135]
https://main--ororafresh--hlxsites.hlx.live/icons/keyboard-arrow.svg

**Comment by meejain** [comment]
Its available now - 

<img width="1777" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/daa7e12a-b601-4d53-bd49-b5534fdafd42">


Keyboard back to top svg is white in colour hence not visible in white background. Please check & validate further @paolomoz
