### ISSUE TITLE
Pics not visible > 768 breakpoint - issue 137

### ISSUE THREAD

**Issue by meejain** [hlxsites/ororafresh#137]
https://main--ororafresh--hlxsites.hlx.live/produce-packaging-solutions

<img width="1099" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/68198500-97dc-4dba-a7a0-a1208c6a98c8">

**Comment by meejain** [comment]
Taken care via - https://github.com/hlxsites/ororafresh/pull/138

Please check & validate further - @paolomoz . Ty again.

**Comment by mtilburgadobe** [comment]
@meejain , change looks good... I was going through the rest of the pages, it looks like we may be missing another image on this page:

https://pics-not-visible-issue-136v1--ororafresh--hlxsites.hlx.live/produce-packaging-automation

Franklin Site:
![Screenshot 2023-07-27 at 11 22 50](https://github.com/hlxsites/ororafresh/assets/77688257/6b9de8d4-f14a-47bc-9f8d-8452ba8d9fae)

Live Site:
![Screenshot 2023-07-27 at 11 22 57](https://github.com/hlxsites/ororafresh/assets/77688257/d01b86e6-497e-473b-9462-4a03e4491191)

**Comment by meejain** [comment]
@mtilburgadobe  - Please check now - https://pics-not-visible-issue-136v1--ororafresh--hlxsites.hlx.live/produce-packaging-automation

**Comment by meejain** [comment]
<img width="1377" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/afa51b72-2abd-4f81-8d4f-28ad9e806c14">
