### ISSUE TITLE
Set up Redirect from http to https (was: Cookie banner does not work with franklin.ororafresh.com)

### ISSUE THREAD

**Issue by mtilburgadobe** [hlxsites/ororafresh#143]
![Screenshot 2023-08-01 at 08 06 29](https://github.com/hlxsites/ororafresh/assets/77688257/1d862577-47b5-4451-b359-351d93eafaea)

**Comment by meejain** [comment]
@mtilburgadobe  - Its working . Please check - 

https://adobe-my.sharepoint.com/:v:/r/personal/meejain_adobe_com/Documents/Recordings/Cookie%20banner%20Troubleshooting-20230801_142641-Meeting%20Recording.mp4?csf=1&web=1&e=9ilLwj&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZyIsInJlZmVycmFsQXBwUGxhdGZvcm0iOiJXZWIiLCJyZWZlcnJhbE1vZGUiOiJ2aWV3In19

<img width="977" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/0bed5be4-5b18-4fc4-b7f3-4676b36dc7b1">

**Comment by mtilburgadobe** [comment]
Happens when you go to the non-secure site: http://franklin.ororafresh.com/

The task here would be to set up a redirect from http://franklin.ororafresh.com/ to https://franklin.ororafresh.com/ in CloudFront

Maybe not important for this url, but for the live url, I believe it should always be https://ororafresh.com (so we'll need redirects from http, as well as www I guess

**Comment by mtilburgadobe** [comment]
@kds-irvine , this only happens when going to the non-secure site, the redirect to make sure that you cannot get to http://franklin.ororafresh.com will need to be done on Cloud Front, @meejain has details.

If this is already set up for ororafresh.com, there may be nothing to do
