### ISSUE TITLE
Mobile Styling - Main Nav

### ISSUE THREAD

**Issue by cody-salazar** [hlxsites/ororafresh#152]
In the mobile view, the main nav is not full-width like the original site. See the screenshots below. Can we get it to match?

Franklin:
![image](https://github.com/hlxsites/ororafresh/assets/100810223/3e2948f9-f0f0-4600-a4aa-c2302a045096)

Orora Fresh: 
![image](https://github.com/hlxsites/ororafresh/assets/100810223/b0633066-c6ad-4d1a-9760-8734f19c6615)

**Comment by meejain** [comment]
@cody-salazar  - Pl check now and let us know if this looks good - https://issue-152--ororafresh--hlxsites.hlx.page/

cc @mtilburgadobe
