### ISSUE TITLE
Some links on home page are returning 404

### ISSUE THREAD

**Issue by kds-irvine** [hlxsites/ororafresh#165]
Several icons under 'Our Process' link to pages returning not found

![image](https://github.com/hlxsites/ororafresh/assets/6031949/c92ef2ff-2412-4d31-8eb1-ec6268a85433)
![image](https://github.com/hlxsites/ororafresh/assets/6031949/a6458cd3-b085-480c-a7e3-7c81d0d891f1)

**Comment by kds-irvine** [comment]
https://ororafresh.com/from-pick-to-pack#from-pick-to-pack-packaging-design is an example of a dead link

**Comment by meejain** [comment]
@kds-irvine  - We have updated those links onto the Franklin word document. However it seems we have not yet completed the cache invalidation action item as per https://www.hlx.live/docs/byo-cdn-cloudfront-setup

Franklin push invalidation automatically purges content on the customer's production CDN (e.g. www.yourdomain.com), whenever an author publishes content changes.

Content is purged by url and by cache tag/key.

Push invalidation is enabled by adding specific properties to the project's configuration (an Excel workbook named .helix/config.xlsx in Sharepoint or a Google Sheet named .helix/config in Google Drive).

NB: CloudFront does NOT support purging by cache tag/key. Purge by cache tag/key always triggers a purge all.

Configuration properties:

key value   comment
cdn.prod.host   <Production Host>   Host name of production site, e.g. www.yourdomain.com
cdn.prod.type   cloudfront  
cdn.prod.distributionId <Cloudfront Distribution ID>    
cdn.prod.accessKeyId    <AWS Access key ID> AWS credentials
cdn.prod.secretAccessKey    <AWS Secret access key> AWS credentials

The moment the above task is done, cache invalidation will take place and we could those links working on the site. 

Regards,

Meet

**Comment by meejain** [comment]
<img width="928" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/e71d5934-b70b-45da-94dc-ef3b2a0b0824">

**Comment by kds-irvine** [comment]
Looks good now
