### ISSUE TITLE
Some links are throwing 404

### ISSUE THREAD

**Issue by KarthikBoreddy** [hlxsites/ororafresh#168]
1. https://www.ororafresh.com/contact-us 

If i click in Navigation contact page it is working, if go https://www.ororafresh.com/produce-packaging-automation and click in lets get started button it throws 404.
<img width="1438" alt="bug1" src="https://github.com/hlxsites/ororafresh/assets/102562257/c506b2aa-5f7c-4dd7-83b5-de4baefd747b">

https://www.ororafresh.com/produce-packaging - Attached screen shot for reference.
<img width="1440" alt="Bug" src="https://github.com/hlxsites/ororafresh/assets/102562257/c5906827-4f1f-4cce-a1ae-ca872df4923d">

2. https://ororafresh.com/wp-content/uploads/2020/01/Orora_Fresh_Product_Brochure.pdf

**Comment by meejain** [comment]
Please check now @KarthikBoreddy  - 

https://www.ororafresh.com/produce-packaging - Lets get started button is working - reaching to contact-us page.
https://www.ororafresh.com/produce-packaging-automation  - Lets get started button is working - reaching to contact-us page.

cc @kds-irvine

**Comment by meejain** [comment]
@KarthikBoreddy  - With regards to https://ororafresh.com/wp-content/uploads/2020/01/Orora_Fresh_Product_Brochure.pdf

do we have any working page / location where these PDF's are located ? We did not notice any wp-content page as such prior.

**Comment by meejain** [comment]
Successfully loaded the pdf into the /media folder on the sharepoint site - https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fororafresh%2Fmedia&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95

https://www.ororafresh.com/media/orora-fresh-product-brochure.pdf is working now.
