### ISSUE TITLE
Cookie preferences image in footer must open cookie preferences

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#32]
<img width="1130" alt="Screenshot 2023-07-03 at 18 02 01" src="https://github.com/hlxsites/ororafresh/assets/111385/30003f73-d538-45c7-a77b-5633f698187b">

**Comment by meejain** [comment]
@paolomoz  - with regards to that cookie preferences - looking at the historical implementation of TrustArc - we need to to include this DIV tag within the Cookie Preferences Link (to be integrated within Footer Links): <div id="teconsent"></div>

Can be very well seen this teconsent ID in the original site - https://ororafresh.com/ . When we get the JS script from TrustArc OR from Google Analytics - that code will search for this DIV which the ID - teconsent and implement the Cooke preferences window. 

Assigning this to myself.

Regards,

Meet

**Comment by meejain** [comment]
@paolomoz  - We removed the cookie preference icon from your footer.docs 

For now added the code for loading the GA + TrustArc JS scripts. Still waiting for the customer response on those JS Scripts. However we figured out the JS scripts from the page source and pour those in. With this Cookie Preference icon came up automatically and giving us the preference window.

Please check & validate further.
