### ISSUE TITLE
Carousel and Hero H1 H2 title positioning

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#61]
<img width="957" alt="Screenshot 2023-07-05 at 14 34 48" src="https://github.com/hlxsites/ororafresh/assets/111385/2e677d01-db4b-45ed-8fa2-eac4f58e1566">
<img width="884" alt="Screenshot 2023-07-06 at 07 15 47" src="https://github.com/hlxsites/ororafresh/assets/111385/5f1f3dc2-e673-4aee-81a4-2c513d7a9ee9">

**Comment by meejain** [comment]
This has been worked upon via https://github.com/hlxsites/ororafresh/pull/75. 

Changed the position & responsiveness of H1 & H2 text within the carousel. Its a lot better now. Please check & validate -

https://hero-carousel-17--ororafresh--hlxsites.hlx.page/Drafts/Meet/

Many Thanks

**Comment by meejain** [comment]
Also noticed that https://ororafresh.com/ - There carousel on Hero is automatically switching the images after 10 seconds, hence implemented a logic.

Please check & validate - https://hero-carousel-17--ororafresh--hlxsites.hlx.page/Drafts/Meet/
