### ISSUE TITLE
Carousel buttons: tap targets are not sized appropriately

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#92]
I guess we should put them a bit further from each other
https://pagespeed.web.dev/analysis/https-main--ororafresh--hlxsites-hlx-live/18wrg5sd25?form_factor=mobile

<img width="1003" alt="Screenshot 2023-07-12 at 15 04 27" src="https://github.com/hlxsites/ororafresh/assets/111385/ba483669-c721-4f56-81e4-62222d3ac6cd">

**Comment by meejain** [comment]
Fixed as per the Pull Requests - https://github.com/hlxsites/ororafresh/pull/95
