### ISSUE TITLE
Carousel titles are below screen fold on Mobile

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#99]
Screens from iPhone

![IMG_6094](https://github.com/hlxsites/ororafresh/assets/111385/8127e8e3-0682-429a-9f85-f877e35d366b)
![IMG_6095](https://github.com/hlxsites/ororafresh/assets/111385/328618a5-a3b2-4fb9-9c4d-6b04ecb6bd9d)

![Uploading IMG_6096.png…]()

**Comment by meejain** [comment]
Please check now - https://cookie-div-issues-111--ororafresh--hlxsites.hlx.page/Drafts/Meet/

On Mobile. Attaching the screen shots.

**Comment by meejain** [comment]
https://github.com/hlxsites/ororafresh/pull/114
